### ISSUE TITLE
please implement "replace" method

### ISSUE THREAD

**Issue by rjbs** [Perl-Critic/PPI#189]
The method `$elem->replace($elem)` is documented but unimplemented.  It would be very useful.  Right now I'm using the undocumented, untested, unused `__replace_child` method, and I feel awful about it.

Please provide a means to do this legitimately.

**Comment by gugod** [comment]
I use `insert_before` + `remove` to achieve replacing element with a manually constructed one.

```perl
$elem->insert_before($new_elem);
$elem->remove;
```

Although I'm not sure if this breaks consistency of the `PPI::Document` object in question, for the purpose of rewriting code, this seems to work.

**Comment by oalders** [comment]
At the very least, maybe the docs could indicate that `replace` is aspirational. I had forgotten about this and it bit me again today.

**Comment by oalders** [comment]
Link to a PR which addresses this https://github.com/Perl-Critic/PPI/pull/254

**Comment by oalders** [comment]
Closed via #254
