### ISSUE TITLE
new contributor

### ISSUE THREAD

**Issue by wchristian** [Perl-Critic/PPI#234]
@adamkennedy Can you please add @charsbar to the repository and give him comaint? My tuit situation is low at the moment, and he has interest and i trust him.

(I'm not stepping out, just trying to increase the team to help the project deal with my limitations.)

**Comment by oalders** [comment]
@charsbar are you still interested?

**Comment by charsbar** [comment]
@oalders I'd be happy to help you though I have less time than before.

**Comment by wchristian** [comment]
@charsbar Collaborator invitation is sent. :)

**Comment by charsbar** [comment]
@wchristian thanks!
