### ISSUE TITLE
Misparse bareword as label

### ISSUE THREAD

**Issue by carygravel** [Perl-Critic/PPI#262]
It is common to have barewords defined by, e.g. Glib:

`use Glib qw(TRUE FALSE);
`

When using a ternary operator, these can be misparsed. PPI 1.270 parses `TRUE :` as a label in the following:

`$result = $result_of_expression ? TRUE : FALSE;
`

instead of identifying the `:` as an operator.

**Comment by oalders** [comment]
```
PPI::Document
  PPI::Statement::Include
    PPI::Token::Word    'use'
    PPI::Token::Whitespace      ' '
    PPI::Token::Word    'Glib'
    PPI::Token::Whitespace      ' '
    PPI::Token::QuoteLike::Words        'qw(TRUE FALSE)'
    PPI::Token::Structure       ';'
  PPI::Token::Whitespace        '\n'
  PPI::Token::Whitespace        '\n'
  PPI::Statement
    PPI::Token::Symbol          '$result'
    PPI::Token::Whitespace      ' '
    PPI::Token::Operator        '='
    PPI::Token::Whitespace      ' '
    PPI::Token::Symbol          '$result_of_expression'
    PPI::Token::Whitespace      ' '
    PPI::Token::Operator        '?'
    PPI::Token::Whitespace      ' '
    PPI::Token::Label   'TRUE :'
    PPI::Token::Whitespace      ' '
    PPI::Token::Word    'FALSE'
    PPI::Token::Structure       ';'
  PPI::Token::Whitespace        '\n'
```

**Comment by h3xx** [comment]
I've run across a similar bug where a terinary was parsed as a P:T:Label.

Adding a newline before the colon stopped it from parsing as a Label.

| Expression | Result
|- | -
| <pre>1 ? $var : 0</pre> | no Label ✅
| <pre>1 ? $var->method : 0</pre> | Label ❌
| <pre>1 ? $var::->method : 0</pre> | Label ❌
| <pre>1 ? var->method : 0</pre> | Label ❌
| <pre>1 ? ($var->method) : 0</pre> | no Label ✅
| <pre>1 ? $var->method <br>: 0</pre> | no Label ✅

Oddly:

| Expression | Result
|- | -
| <pre>$var ? TRUE : FALSE</pre> | Label ❌
| <pre>$var ? 1 : 0</pre> | no Label ✅

PPI version 1.276.

**Comment by oalders** [comment]
If someone wanted to put together a patch to fix this, that would be great.

**Comment by h3xx** [comment]
I have fix submitted in #289. Can you let me know if this fixes your issue.

Also, could you *especially* let me know if this causes any other issues. 😄

**Comment by wchristian** [comment]
fwiw, i hope to be past the worst in my current $work project by wednesday and will do some review then :)

**Comment by h3xx** [comment]
@wchristian Any luck?
